language: bash

script:
    - bash create_package.sh && bash automatron.sh && PATH=$HOME/miniconda/bin:$PATH python -c 'import ansible, platform; print platform.python_version()'
    - bash create_package.sh -p 3 && bash automatron.sh -- -f -f && PATH=$HOME/miniconda/bin:$PATH python -c 'import ansible, platform; print(platform.python_version())' && rm -rf $HOME/miniconda
    - echo "ansible" >> requirements.txt && bash create_package.sh -r requirements.txt && bash automatron.sh && PATH=$HOME/miniconda/bin:$PATH python -c 'import ansible, platform; print platform.python_version()'
